"""Add user_id foreign key to emails

Revision ID: d8d310acc842
Revises: cf80a859bb93
Create Date: 2026-06-20 13:48:02.673876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8d310acc842'
down_revision: Union[str, Sequence[str], None] = 'cf80a859bb93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_emails_user_id'), 'emails', ['user_id'], unique=False)
    op.create_foreign_key(None, 'emails', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_index(op.f('ix_emails_user_id'), table_name='emails')
    op.drop_column('emails', 'user_id')
    # ### end Alembic commands ###
