"""Add gmail_message_id to emails

Revision ID: e28b305e983a
Revises: 9af5e8e8c6e8
Create Date: 2026-06-28 16:54:18.690664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e28b305e983a'
down_revision: Union[str, Sequence[str], None] = '9af5e8e8c6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('gmail_message_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_emails_gmail_message_id'), 'emails', ['gmail_message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_gmail_message_id'), table_name='emails')
    op.drop_column('emails', 'gmail_message_id')
    # ### end Alembic commands ###
